import { type NextPage } from "next";
import { useSession } from "next-auth/react";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect } from "react";
import { Posts } from "~/components/posts";
const PageContent: NextPage = () => {
  const { status } = useSession();
  const router = useRouter();
  useEffect(() => {
    const toHome = async () => {
      await router.replace("/");
    };
    if (status == "unauthenticated")
      toHome().catch(() => {
        return;
      });
  }, [status]);
  return (
    <>
      <Head>
        <title>Mediashare</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="m-2 bg-white p-4 shadow-md">
          <div>
            <Posts yourFollwing={true} />
          </div>
        </div>
      </main>
    </>
  );
};

export default PageContent;
