import { type NextPage } from "next";
import Head from "next/head";
import { CreatePost } from "~/components/form/createPost";
import { Posts } from "~/components/posts";
import Auth from "~/components/auth";
import Search from "~/components/search";

const PageContent: NextPage = () => {
  return (
    <>
      <Head>
        <title>Mediashare</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="m-2 bg-white p-4 shadow-md">
          <div className="flex items-center justify-end ">
            <div className="w-1/4 transition-width duration-100 ease-in hover:w-full md:hover:w-1/2">
              <Search />
            </div>
          </div>
          <Auth>
            <CreatePost />
            <div className="mt-4 border-t border-gray-200 pt-4"></div>
          </Auth>

          <div>
            <Posts />
          </div>
        </div>
      </main>
    </>
  );
};

export default PageContent;
