import { UploadButton } from "@uploadthing/react";
import type { OurFileRouter } from "~/server/uploadthing";

import { useRef } from "react";
import { type NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  const startUploadRef = useRef<(() => void) | null>(null);
  const handleStartUpload = (startUpload: () => void) => {
    startUploadRef.current = startUpload;
  };
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <form>
          <textarea
            className="bg-gray-100 text-black"
            placeholder="What's on your mind?"
          ></textarea>
        </form>
        <button
          onClick={() => {
            console.log("startUploadCall", startUploadRef);
            if (startUploadRef.current) startUploadRef.current();
          }}
        >
          This should now upload :{")"}{" "}
        </button>
        <UploadButton<OurFileRouter>
          endpoint="postUploader"
          startUpload={handleStartUpload}
          onClientUploadComplete={(res) => {
            // Do something with the response
            console.log("Files: ", res);
            alert("Post created! (with upload)");
          }}
          onUploadError={(error: Error) => {
            // Do something with the error.
            alert(`ERROR! ${error.message} ${JSON.stringify(error)}`);
          }}
        />
      </main>
    </>
  );
};

export default Home;
