import Head from "next/head";
import { useRouter } from "next/router";
import { Posts } from "~/components/posts";
import { MainPost } from "~/components/comment";
import Sidebar from "~/components/sidebar";
import { api } from "~/utils/api";

type params = {
  commentId: string;
};

function Comment() {
  const params = useRouter().query as params;
  const post = api.posts.getOne.useQuery({ id: params.commentId });

  return (
    <>
      <Head>
        <title>Twitter - </title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Sidebar>
          {!post.isSuccess ? (
            <p>Loading...</p>
          ) : (
            <>
              <MainPost post={post.data} />
              <Posts mainPostId={post.data.id}></Posts>
            </>
          )}
        </Sidebar>
      </main>
    </>
  );
}

export default Comment;
