import Head from "next/head";
import { useRouter } from "next/router";
import { Posts } from "~/components/posts";
import { MainPost } from "~/components/comment";

import { api } from "~/utils/api";
import { CreateComent } from "~/components/form/createComment";
import Loading from "~/components/loading";

type params = {
  commentId: string;
};

function Comment() {
  const params = useRouter().query as params;
  const post = api.posts.getOne.useQuery({ id: params.commentId });

  return (
    <>
      <Head>
        <title>Mediashare</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {!post.isSuccess ? (
          <Loading />
        ) : (
          <>
            <MainPost post={post.data} />

            <CreateComent
              howManyComments={post.data._count.Comment}
              postId={post.data.id}
            />
            <Posts mainPostId={post.data.id}></Posts>
          </>
        )}
      </main>
    </>
  );
}

export default Comment;
