import type { NextPage } from "next";
import { useSession } from "next-auth/react";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import Sidebar from "~/components/sidebar";
type params = {
  userName: string;
};
const PageContent: NextPage = () => {
  const { data: session } = useSession();
  const params = useRouter().query as params;
  return (
    <>
      <Head>
        <title>Twitter - {params.userName}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Sidebar>
          <div className="flex h-full w-full justify-center">
            <div className="m-2 w-full max-w-[1546px] bg-white  shadow-md">
              <div className="flex h-1/3 max-h-[432px] items-start justify-center bg-slate-600">
                <Image
                  src={
                    "https://images.pexels.com/photos/573130/pexels-photo-573130.jpeg?auto=compress&cs=tinysrgb&w=1600"
                  }
                  alt={"Image"}
                  width={1546}
                  height={432}
                  className={"max-h-full object-scale-down "}
                ></Image>
              </div>
            </div>
          </div>
        </Sidebar>
      </main>
    </>
  );
};

export default PageContent;
