import { UploadButton } from "@uploadthing/react";
import type { OurFileRouter } from "~/server/uploadthing";

import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const Home: NextPage = () => {
  const userSubmit = (e: React.FormEvent<HTMLFormElement>) => {};
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <form onSubmit={userSubmit}>
          <textarea
            className="bg-gray-100 text-black"
            placeholder="What's on your mind?"
          ></textarea>
        </form>
        <UploadButton<OurFileRouter>
          endpoint="imageUploader"
          onClientUploadComplete={(res) => {
            // Do something with the response
            console.log("Files: ", res);
            alert("Post created! (with upload)");
          }}
          onUploadError={(error: Error) => {
            // Do something with the error.
            alert(`ERROR! ${error.message} ${JSON.stringify(error)}`);
          }}
        />
      </main>
    </>
  );
};

export default Home;
